# Generated by Django 4.1 on 2023-05-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="appCycle",
            fields=[
                ("appCycle_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="JobRecruiter",
            fields=[
                (
                    "jobRecruiter_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                ("jobSeeker_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("position_id", models.AutoField(primary_key=True, serialize=False)),
                ("position_number", models.CharField(max_length=20)),
                ("position_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("season_id", models.AutoField(primary_key=True, serialize=False)),
                ("season_sequence", models.IntegerField(unique=True)),
                ("season_name", models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                ("year_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "appCycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company",
                        to="jobinfo.appcycle",
                    ),
                ),
                (
                    "jobRecruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company",
                        to="jobinfo.jobrecruiter",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company",
                        to="jobinfo.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application",
                        to="jobinfo.company",
                    ),
                ),
                (
                    "jobSeeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application",
                        to="jobinfo.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appcycle",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appCycle",
                to="jobinfo.season",
            ),
        ),
        migrations.AddField(
            model_name="appcycle",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appCycle",
                to="jobinfo.year",
            ),
        ),
    ]
