# Generated by Django 4.1 on 2023-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appcycle",
            options={"ordering": ["year__year", "season__season_sequence"]},
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["company", "jobSeeker"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["position", "company_name", "appCycle"]},
        ),
        migrations.AlterModelOptions(
            name="jobrecruiter",
            options={"ordering": ["last_name", "first_name", "disambiguator"]},
        ),
        migrations.AlterModelOptions(
            name="jobseeker",
            options={"ordering": ["last_name", "first_name", "disambiguator"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["position_number", "position_name"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["season_sequence"]},
        ),
        migrations.AlterModelOptions(
            name="year",
            options={"ordering": ["year"]},
        ),
        migrations.AddConstraint(
            model_name="appcycle",
            constraint=models.UniqueConstraint(
                fields=("year", "season"), name="unique_appCycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("company", "jobSeeker"), name="unique_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("appCycle", "position", "company_name"), name="unique_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobrecruiter",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_jobRecruiter",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobseeker",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "disambiguator"),
                name="unique_jobSeeker",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("position_number", "position_name"), name="unique_position"
            ),
        ),
    ]
