# Generated by Django 4.1 on 2023-05-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobinfo", "0004_load_jobSeeker_test_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appcycle",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appCycles",
                to="jobinfo.season",
            ),
        ),
        migrations.AlterField(
            model_name="appcycle",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appCycles",
                to="jobinfo.year",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="jobinfo.company",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="jobSeeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="jobinfo.jobseeker",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="appCycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="jobinfo.appcycle",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="jobRecruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="jobinfo.jobrecruiter",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companies",
                to="jobinfo.position",
            ),
        ),
    ]
