from django.urls import path

from jobinfo.views import (
    JobRecruiterList,
    CompanyList,
    JobSeekerList,
    PositionList,
    AppCycleList,
    ApplicationList, JobRecruiterDetail, CompanyDetail, JobSeekerDetail, AppCycleDetail, PositionDetail,
    ApplicationDetail,
    JobRecruiterCreate,
    CompanyCreate,
    PositionCreate,
    AppCycleCreate,
    JobSeekerCreate,
    ApplicationCreate,
    JobRecruiterUpdate, CompanyUpdate, PositionUpdate, AppCycleUpdate, JobSeekerUpdate, ApplicationUpdate,
    ApplicationDelete, JobRecruiterDelete, CompanyDelete, PositionDelete, AppCycleDelete, JobSeekerDelete,
)


urlpatterns = [
    path('jobRecruiter/', JobRecruiterList.as_view(),
         name='jobinfo_jobRecruiter_list_urlpattern'),
    path('jobRecruiter/<int:pk>/', JobRecruiterDetail.as_view(),
         name='jobinfo_jobRecruiter_detail_urlpattern'),
    path('jobRecruiter/create/',
         JobRecruiterCreate.as_view(),
         name='jobinfo_jobRecruiter_create_urlpattern'),
    path('jobRecruiter/<int:pk>/update/',
         JobRecruiterUpdate.as_view(),
         name='jobinfo_jobRecruiter_update_urlpattern'),
    path('jobRecruiter/<int:pk>/delete/',
         JobRecruiterDelete.as_view(),
         name='jobinfo_jobRecruiter_delete_urlpattern'),
    path('company/', CompanyList.as_view(),
         name='jobinfo_company_list_urlpattern'),
    path('company/<int:pk>', CompanyDetail.as_view(),
         name='jobinfo_company_detail_urlpattern'),
    path('company/create/',
         CompanyCreate.as_view(),
         name='jobinfo_company_create_urlpattern'),
    path('company/<int:pk>/update/',
         CompanyUpdate.as_view(),
         name='jobinfo_company_update_urlpattern'),
    path('company/<int:pk>/delete/',
         CompanyDelete.as_view(),
         name='jobinfo_company_delete_urlpattern'),
    path('position/', PositionList.as_view(),
         name='jobinfo_position_list_urlpattern'),
    path('position/<int:pk>', PositionDetail.as_view(),
         name='jobinfo_position_detail_urlpattern'),
    path('position/create/',
         PositionCreate.as_view(),
         name='jobinfo_position_create_urlpattern'),
    path('position/<int:pk>/update/',
         PositionUpdate.as_view(),
         name='jobinfo_position_update_urlpattern'),
    path('position/<int:pk>/delete/',
         PositionDelete.as_view(),
         name='jobinfo_position_delete_urlpattern'),
    path('appCycle/', AppCycleList.as_view(),
         name='jobinfo_appCycle_list_urlpattern'),
    path('appCycle/<int:pk>', AppCycleDetail.as_view(),
         name='jobinfo_appCycle_detail_urlpattern'),
    path('appCycle/create/',
         AppCycleCreate.as_view(),
         name='jobinfo_appCycle_create_urlpattern'),
    path('appCycle/<int:pk>/update/',
         AppCycleUpdate.as_view(),
         name='jobinfo_appCycle_update_urlpattern'),
    path('appCycle/<int:pk>/delete/',
         AppCycleDelete.as_view(),
         name='jobinfo_appCycle_delete_urlpattern'),
    path('jobSeeker/', JobSeekerList.as_view(),
         name='jobinfo_jobSeeker_list_urlpattern'),
    path('jobSeeker/<int:pk>/', JobSeekerDetail.as_view(),
         name='jobinfo_jobSeeker_detail_urlpattern'),
    path('jobSeeker/create/',
         JobSeekerCreate.as_view(),
         name='jobinfo_jobSeeker_create_urlpattern'),
    path('jobSeeker/<int:pk>/update/',
         JobSeekerUpdate.as_view(),
         name='jobinfo_jobSeeker_update_urlpattern'),
    path('jobSeeker/<int:pk>/delete/',
         JobSeekerDelete.as_view(),
         name='jobinfo_jobSeeker_delete_urlpattern'),
    path('application/', ApplicationList.as_view(),
         name='jobinfo_application_list_urlpattern'),
    path('application/<int:pk>', ApplicationDetail.as_view(),
         name='jobinfo_application_detail_urlpattern'),
    path('application/create/',
         ApplicationCreate.as_view(),
         name='jobinfo_application_create_urlpattern'),
    path('application/<int:pk>/update/',
         ApplicationUpdate.as_view(),
         name='jobinfo_application_update_urlpattern'),
    path('application/<int:pk>/delete/',
         ApplicationDelete.as_view(),
         name='jobinfo_application_delete_urlpattern'),
]


